spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://service.aliww.top:3306/shixun_mr?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jalivv666
server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.jalivv.mry: debug
